### PR TITLE
Create dependabot.yml

### PR DESCRIPTION
**Pull request by tschm**
Use a bot to keep your Github Actions up-to-date

### CODE REVIEW

**Comment by 12rambau** [comment]
I activated it this morning from GitHub settings side, it's already activated on other repositories I maintain and I never felt the need to add a config file, what is the added value compared to the default behaviour? (I never though much about it)

**Comment by tschm** [comment]
I could be wrong but in the settings you only activate dependabot. You need a config file for it though. With that file dependabot knows that it should look for. Once you merged that into, you will see dependabot creating pull requests. Give it a go

**Comment by tschm** [comment]
Warnings as in https://github.com/12rambau/pytest-copie/actions/runs/8104427212 will disappear as the bot keeps your actions up-to-date.

**Comment by tschm** [comment]
Not sure I can follow. In pydata-sphinx there is https://github.com/pydata/pydata-sphinx-theme/blob/main/.github/dependabot.yml

Make sure the dependabot.yml file has to be in the .github folder. Nothing happens with magic and the magic results only in pull requests you can still refuse.

**Comment by 12rambau** [comment]
Thanks for waiting !

**Pull request merged**
